### ISSUE TITLE
No such file or directory: 'output/all_reports.json'

### ISSUE THREAD

**Issue by V35HR4J** [h1pmnh/h1reports#1]
HI,
i got following error while trying it:
```
Traceback (most recent call last):
  File "./h1reports", line 294, in <module>
    reports = get_all_reports(args)
  File "./h1reports", line 68, in get_all_reports
    with open("%s/all_reports.json" % args.directory, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/all_reports.json'
```

would appreciate if you could look into it.
<img width="680" alt="Screen Shot 2022-09-28 at 6 24 43 PM" src="https://user-images.githubusercontent.com/54109630/192781345-a094e7aa-a8f7-44e3-a9c4-c08db627d085.png">

**Comment by V35HR4J** [comment]
By default it is not making the directory output,
i fixed it by creating directory `output` and keeping `all_reports.json` inside it.

Thanks again for cool tool :)

**Comment by h1pmnh** [comment]
Thanks, I'll do a bug fix to have it create the directory if it doesn't exist. I'll leave this open until I get that done :)

**Comment by h1pmnh** [comment]
Resolved, thanks again for the feedback :)
